import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'tailwindcss/tailwind.css';
import { useState, useEffect } from "react";
import Web3 from "web3";
export default function Home() {
    const [ a, setA ] = useState("ID")
    const onChangeA = (e) => {setA(e.target.value)}
    const [ b, setB ] = useState("ID")
    const onChangeB = (e) => {setB(e.target.value)}
    const [ c, setC ] = useState("ID")
    const onChangeC = (e) => {setC(e.target.value)}
    const [ d, setD ] = useState("ID")
    const onChangeD = (e) => {setD(e.target.value)}

    let style = {
      borderRadius: "0px",
      padding: "5px",
      margin:"20px"
    }
    let classT = "w-20 h-20 text-center bg-[#ffffff] font-bold text-xl"
  return (
    <div className="m-0">
      <Head>
        <title>Flows Life</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full h-[100vh] bg-[#000000] m-0 p-0 flex items-center justify-center">
          <div className="flex flex-col space-y-10 items-center">
            <div className="flex flex-rows space-x-10">
                  <input  className={classT} name="a" value={a} onChange={onChangeA} />
                  <input  className={classT} name="b" value={b} onChange={onChangeB} />
                  
            </div>
            <div className="flex flex-rows space-x-10">
                <input className={classT} name="c" value={c} onChange={onChangeC} />
                  <input  className={classT} name="d" value={d} onChange={onChangeD} />
            </div>
            <button className={classT+" w-full"} onClick={() => {
              if(typeof globalThis.ethereum !== "undefined"){
                if (globalThis.web3 !== "undefined" && globalThis.ethereum.selectedAddress != null && globalThis.ethereum.selectedAddress != "" && globalThis.ethereum.selectedAddress != undefined) {
                  globalThis.ethereum.enable().then(()=>{
                    let web3js = new Web3(globalThis.web3.currentProvider); 
                    web3js.eth.net.getId().then((chainId) => {
                      if(chainId !=80001) alert("Please use polygon");
                      web3js.eth.getAccounts().then((x)=>{
                        
                        let account = globalThis.ethereum.selectedAddress;
                        let contract = new web3js.eth.Contract([
                          {
                            "inputs": [],
                            "stateMutability": "nonpayable",
                            "type": "constructor"
                          },
                          {
                            "anonymous": false,
                            "inputs": [
                              {
                                "indexed": true,
                                "internalType": "address",
                                "name": "owner",
                                "type": "address"
                              },
                              {
                                "indexed": true,
                                "internalType": "address",
                                "name": "approved",
                                "type": "address"
                              },
                              {
                                "indexed": true,
                                "internalType": "uint256",
                                "name": "tokenId",
                                "type": "uint256"
                              }
                            ],
                            "name": "Approval",
                            "type": "event"
                          },
                          {
                            "anonymous": false,
                            "inputs": [
                              {
                                "indexed": true,
                                "internalType": "address",
                                "name": "owner",
                                "type": "address"
                              },
                              {
                                "indexed": true,
                                "internalType": "address",
                                "name": "operator",
                                "type": "address"
                              },
                              {
                                "indexed": false,
                                "internalType": "bool",
                                "name": "approved",
                                "type": "bool"
                              }
                            ],
                            "name": "ApprovalForAll",
                            "type": "event"
                          },
                          {
                            "anonymous": false,
                            "inputs": [
                              {
                                "indexed": true,
                                "internalType": "address",
                                "name": "previousOwner",
                                "type": "address"
                              },
                              {
                                "indexed": true,
                                "internalType": "address",
                                "name": "newOwner",
                                "type": "address"
                              }
                            ],
                            "name": "OwnershipTransferred",
                            "type": "event"
                          },
                          {
                            "anonymous": false,
                            "inputs": [
                              {
                                "indexed": true,
                                "internalType": "address",
                                "name": "from",
                                "type": "address"
                              },
                              {
                                "indexed": true,
                                "internalType": "address",
                                "name": "to",
                                "type": "address"
                              },
                              {
                                "indexed": true,
                                "internalType": "uint256",
                                "name": "tokenId",
                                "type": "uint256"
                              }
                            ],
                            "name": "Transfer",
                            "type": "event"
                          },
                          {
                            "inputs": [],
                            "name": "Gen1",
                            "outputs": [
                              {
                                "internalType": "address",
                                "name": "",
                                "type": "address"
                              }
                            ],
                            "stateMutability": "view",
                            "type": "function"
                          },
                          {
                            "inputs": [
                              {
                                "internalType": "uint256",
                                "name": "a",
                                "type": "uint256"
                              },
                              {
                                "internalType": "uint256",
                                "name": "b",
                                "type": "uint256"
                              },
                              {
                                "internalType": "uint256",
                                "name": "c",
                                "type": "uint256"
                              },
                              {
                                "internalType": "uint256",
                                "name": "d",
                                "type": "uint256"
                              }
                            ],
                            "name": "MintFromGen1",
                            "outputs": [],
                            "stateMutability": "nonpayable",
                            "type": "function"
                          },
                          {
                            "inputs": [
                              {
                                "internalType": "uint256",
                                "name": "a",
                                "type": "uint256"
                              },
                              {
                                "internalType": "uint256",
                                "name": "b",
                                "type": "uint256"
                              },
                              {
                                "internalType": "uint256",
                                "name": "c",
                                "type": "uint256"
                              },
                              {
                                "internalType": "uint256",
                                "name": "d",
                                "type": "uint256"
                              }
                            ],
                            "name": "MintFromGen2",
                            "outputs": [],
                            "stateMutability": "nonpayable",
                            "type": "function"
                          },
                          {
                            "inputs": [
                              {
                                "internalType": "address",
                                "name": "to",
                                "type": "address"
                              },
                              {
                                "internalType": "uint256",
                                "name": "tokenId",
                                "type": "uint256"
                              }
                            ],
                            "name": "approve",
                            "outputs": [],
                            "stateMutability": "nonpayable",
                            "type": "function"
                          },
                          {
                            "inputs": [
                              {
                                "internalType": "address",
                                "name": "owner",
                                "type": "address"
                              }
                            ],
                            "name": "balanceOf",
                            "outputs": [
                              {
                                "internalType": "uint256",
                                "name": "",
                                "type": "uint256"
                              }
                            ],
                            "stateMutability": "view",
                            "type": "function"
                          },
                          {
                            "inputs": [
                              {
                                "internalType": "uint256",
                                "name": "",
                                "type": "uint256"
                              }
                            ],
                            "name": "breedsGen1",
                            "outputs": [
                              {
                                "internalType": "uint256",
                                "name": "",
                                "type": "uint256"
                              }
                            ],
                            "stateMutability": "view",
                            "type": "function"
                          },
                          {
                            "inputs": [
                              {
                                "internalType": "uint256",
                                "name": "",
                                "type": "uint256"
                              }
                            ],
                            "name": "breedsGen2",
                            "outputs": [
                              {
                                "internalType": "uint256",
                                "name": "",
                                "type": "uint256"
                              }
                            ],
                            "stateMutability": "view",
                            "type": "function"
                          },
                          {
                            "inputs": [
                              {
                                "internalType": "string",
                                "name": "",
                                "type": "string"
                              }
                            ],
                            "name": "exists",
                            "outputs": [
                              {
                                "internalType": "bool",
                                "name": "",
                                "type": "bool"
                              }
                            ],
                            "stateMutability": "view",
                            "type": "function"
                          },
                          {
                            "inputs": [
                              {
                                "internalType": "string",
                                "name": "input",
                                "type": "string"
                              }
                            ],
                            "name": "fromBinaryString",
                            "outputs": [
                              {
                                "internalType": "uint256",
                                "name": "",
                                "type": "uint256"
                              }
                            ],
                            "stateMutability": "pure",
                            "type": "function"
                          },
                          {
                            "inputs": [
                              {
                                "internalType": "uint256",
                                "name": "tokenId",
                                "type": "uint256"
                              }
                            ],
                            "name": "getApproved",
                            "outputs": [
                              {
                                "internalType": "address",
                                "name": "",
                                "type": "address"
                              }
                            ],
                            "stateMutability": "view",
                            "type": "function"
                          },
                          {
                            "inputs": [
                              {
                                "internalType": "address",
                                "name": "owner",
                                "type": "address"
                              },
                              {
                                "internalType": "address",
                                "name": "operator",
                                "type": "address"
                              }
                            ],
                            "name": "isApprovedForAll",
                            "outputs": [
                              {
                                "internalType": "bool",
                                "name": "",
                                "type": "bool"
                              }
                            ],
                            "stateMutability": "view",
                            "type": "function"
                          },
                          {
                            "inputs": [],
                            "name": "name",
                            "outputs": [
                              {
                                "internalType": "string",
                                "name": "",
                                "type": "string"
                              }
                            ],
                            "stateMutability": "view",
                            "type": "function"
                          },
                          {
                            "inputs": [],
                            "name": "owner",
                            "outputs": [
                              {
                                "internalType": "address",
                                "name": "",
                                "type": "address"
                              }
                            ],
                            "stateMutability": "view",
                            "type": "function"
                          },
                          {
                            "inputs": [
                              {
                                "internalType": "uint256",
                                "name": "tokenId",
                                "type": "uint256"
                              }
                            ],
                            "name": "ownerOf",
                            "outputs": [
                              {
                                "internalType": "address",
                                "name": "",
                                "type": "address"
                              }
                            ],
                            "stateMutability": "view",
                            "type": "function"
                          },
                          {
                            "inputs": [],
                            "name": "paused",
                            "outputs": [
                              {
                                "internalType": "bool",
                                "name": "",
                                "type": "bool"
                              }
                            ],
                            "stateMutability": "view",
                            "type": "function"
                          },
                          {
                            "inputs": [],
                            "name": "renounceOwnership",
                            "outputs": [],
                            "stateMutability": "nonpayable",
                            "type": "function"
                          },
                          {
                            "inputs": [
                              {
                                "internalType": "address",
                                "name": "from",
                                "type": "address"
                              },
                              {
                                "internalType": "address",
                                "name": "to",
                                "type": "address"
                              },
                              {
                                "internalType": "uint256",
                                "name": "tokenId",
                                "type": "uint256"
                              }
                            ],
                            "name": "safeTransferFrom",
                            "outputs": [],
                            "stateMutability": "nonpayable",
                            "type": "function"
                          },
                          {
                            "inputs": [
                              {
                                "internalType": "address",
                                "name": "from",
                                "type": "address"
                              },
                              {
                                "internalType": "address",
                                "name": "to",
                                "type": "address"
                              },
                              {
                                "internalType": "uint256",
                                "name": "tokenId",
                                "type": "uint256"
                              },
                              {
                                "internalType": "bytes",
                                "name": "data",
                                "type": "bytes"
                              }
                            ],
                            "name": "safeTransferFrom",
                            "outputs": [],
                            "stateMutability": "nonpayable",
                            "type": "function"
                          },
                          {
                            "inputs": [
                              {
                                "internalType": "address",
                                "name": "operator",
                                "type": "address"
                              },
                              {
                                "internalType": "bool",
                                "name": "approved",
                                "type": "bool"
                              }
                            ],
                            "name": "setApprovalForAll",
                            "outputs": [],
                            "stateMutability": "nonpayable",
                            "type": "function"
                          },
                          {
                            "inputs": [
                              {
                                "internalType": "string",
                                "name": "baseuri",
                                "type": "string"
                              }
                            ],
                            "name": "setBaseURI",
                            "outputs": [],
                            "stateMutability": "nonpayable",
                            "type": "function"
                          },
                          {
                            "inputs": [
                              {
                                "internalType": "address",
                                "name": "gen1Address",
                                "type": "address"
                              }
                            ],
                            "name": "setGen1",
                            "outputs": [],
                            "stateMutability": "nonpayable",
                            "type": "function"
                          },
                          {
                            "inputs": [
                              {
                                "internalType": "bool",
                                "name": "state",
                                "type": "bool"
                              }
                            ],
                            "name": "setPaused",
                            "outputs": [],
                            "stateMutability": "nonpayable",
                            "type": "function"
                          },
                          {
                            "inputs": [
                              {
                                "internalType": "bytes4",
                                "name": "interfaceId",
                                "type": "bytes4"
                              }
                            ],
                            "name": "supportsInterface",
                            "outputs": [
                              {
                                "internalType": "bool",
                                "name": "",
                                "type": "bool"
                              }
                            ],
                            "stateMutability": "view",
                            "type": "function"
                          },
                          {
                            "inputs": [],
                            "name": "symbol",
                            "outputs": [
                              {
                                "internalType": "string",
                                "name": "",
                                "type": "string"
                              }
                            ],
                            "stateMutability": "view",
                            "type": "function"
                          },
                          {
                            "inputs": [
                              {
                                "internalType": "uint256",
                                "name": "n",
                                "type": "uint256"
                              }
                            ],
                            "name": "toBinaryString",
                            "outputs": [
                              {
                                "internalType": "string",
                                "name": "",
                                "type": "string"
                              }
                            ],
                            "stateMutability": "pure",
                            "type": "function"
                          },
                          {
                            "inputs": [
                              {
                                "internalType": "uint256",
                                "name": "index",
                                "type": "uint256"
                              }
                            ],
                            "name": "tokenByIndex",
                            "outputs": [
                              {
                                "internalType": "uint256",
                                "name": "",
                                "type": "uint256"
                              }
                            ],
                            "stateMutability": "view",
                            "type": "function"
                          },
                          {
                            "inputs": [
                              {
                                "internalType": "string",
                                "name": "uri",
                                "type": "string"
                              }
                            ],
                            "name": "tokenClean",
                            "outputs": [
                              {
                                "internalType": "string",
                                "name": "",
                                "type": "string"
                              }
                            ],
                            "stateMutability": "view",
                            "type": "function"
                          },
                          {
                            "inputs": [
                              {
                                "internalType": "address",
                                "name": "owner",
                                "type": "address"
                              },
                              {
                                "internalType": "uint256",
                                "name": "index",
                                "type": "uint256"
                              }
                            ],
                            "name": "tokenOfOwnerByIndex",
                            "outputs": [
                              {
                                "internalType": "uint256",
                                "name": "",
                                "type": "uint256"
                              }
                            ],
                            "stateMutability": "view",
                            "type": "function"
                          },
                          {
                            "inputs": [
                              {
                                "internalType": "uint256",
                                "name": "tokenId",
                                "type": "uint256"
                              }
                            ],
                            "name": "tokenURI",
                            "outputs": [
                              {
                                "internalType": "string",
                                "name": "",
                                "type": "string"
                              }
                            ],
                            "stateMutability": "view",
                            "type": "function"
                          },
                          {
                            "inputs": [],
                            "name": "totalSupply",
                            "outputs": [
                              {
                                "internalType": "uint256",
                                "name": "",
                                "type": "uint256"
                              }
                            ],
                            "stateMutability": "view",
                            "type": "function"
                          },
                          {
                            "inputs": [
                              {
                                "internalType": "address",
                                "name": "from",
                                "type": "address"
                              },
                              {
                                "internalType": "address",
                                "name": "to",
                                "type": "address"
                              },
                              {
                                "internalType": "uint256",
                                "name": "tokenId",
                                "type": "uint256"
                              }
                            ],
                            "name": "transferFrom",
                            "outputs": [],
                            "stateMutability": "nonpayable",
                            "type": "function"
                          },
                          {
                            "inputs": [
                              {
                                "internalType": "address",
                                "name": "newOwner",
                                "type": "address"
                              }
                            ],
                            "name": "transferOwnership",
                            "outputs": [],
                            "stateMutability": "nonpayable",
                            "type": "function"
                          },
                          {
                            "inputs": [
                              {
                                "internalType": "uint256",
                                "name": "",
                                "type": "uint256"
                              }
                            ],
                            "name": "uriend",
                            "outputs": [
                              {
                                "internalType": "string",
                                "name": "",
                                "type": "string"
                              }
                            ],
                            "stateMutability": "view",
                            "type": "function"
                          }
                        ],"0xBf2DeA43b41449d27266b32eC7A3B84457014182");
                        web3js.eth.getGasPrice(function(e, r) {
                          contract.methods.MintFromGen1(parseInt(a),parseInt(c),parseInt(b),parseInt(d)).send(
                            {
                              from: account,
                             // gas: 624712,
                              gasPrice: r
                            }
                          ).then(() => {console.log("Done")});
                        })
                        
                      });
                    });
                    
                  });
                  
                  
                }else{
                  alert("Please install metamask");
                }
              }else{
                alert("Please install metamask");
              }
            }}>BREED</button>
            <h3 className="text-[#fff] text-xs aligne-center">Each Gen1 can be breeded 8 times</h3>
          </div>
      </main>

    </div>
  )
}
